### PR TITLE
Adding author

### PR DESCRIPTION
**Pull request by whockey**

### CODE REVIEW

**Comment by WaleedJubeh** [comment]
Great feature

**Comment by whockey** [comment]
Hey great code!

**Comment by samerkh** [comment]
good feature

**Comment by NullOsama** [comment]
hey!!

**Comment by DeemaAdgesh** [comment]
comment xD

**Comment by HerbawiAmir** [comment]
nice add

**Comment by MaryamShaheen** [comment]
keep it up

**Comment by SondosJamal** [comment]
hello

**Comment by IyadWalweel** [comment]
May you change the author name to full name please

**Comment by Shoman0087** [comment]
nice feature

**Comment by AyahSoufan** [comment]
We are good to ship!

**Comment by MarahAshayer** [comment]
Hello

**Comment by basilatawneh** [comment]
useful feature

**Comment by Zaidanebreak** [comment]
yes it makes since

**Pull request merged**
